### ISSUE TITLE
ERROR : failed to open the HDF5 file "Data_000000" !!    

### ISSUE THREAD

**Issue by CrazyAncestor** [gamer-project/gamer#59] opened 2021-06-28 04:31 UTC
I was testing on NFW test problem and found this error while running
ERROR : failed to open the HDF5 file "Data_000000" !!
        Rank <0>, file <Output/Output_DumpData_Total_HDF5.cpp>, line <972>, function <Output_DumpData_Total_HDF5>
The attached file is the log file
[log.txt](https://github.com/gamer-project/gamer/files/6723397/log.txt)

**Comment by hyschive** [comment] 2021-06-28 11:27
This is caused by incorrectly using MPI to run GAMER with `SERIAL` on. So I'll close this issue.

**Closed by hyschive** 2021-06-28 11:27 UTC
