### ISSUE TITLE
Unusual instabilities in ClusterMerger problem with MHD

### ISSUE THREAD

**Issue by jzuhone** [gamer-project/gamer#80] opened 2021-09-18 15:02 UTC
The current version of GAMER results in some unusual instabilities in the `ClusterMerger` test problem when using the example parameters and input data, see this notebook:

https://gist.github.com/235c9bfa21ae854d6176e4bd27447630

@hyschive I've found that changing the radial profile of the gas density to something more sensible has no effect on this. I can try bisecting the code to find out when the instabilities were introduced.

**Comment by jzuhone** [comment] 2021-09-18 15:06
These instabilities are also present in the code from before the recent flux correction commits on September 5th, so that does not appear to be the issue.

**Comment by hyschive** [comment] 2021-09-19 03:01
@jzuhone Thanks for reporting this issue. Are you referring to the density fragmentation in the cluster on the right?

> I can try bisecting the code to find out when the instabilities were introduced.

That will be very helpful. I will help fix it once the problematic commits are identified.

**Comment by jzuhone** [comment] 2021-09-19 03:28
> Are you referring to the density fragmentation in the cluster on the right?

Yes, which occurs because the magnetic field becomes wildly unstable.

**Comment by jzuhone** [comment] 2021-09-21 02:06
So this is apparently an issue with my compiler options--this occurred when I enabled `-std=c++11` for some reason. When I removed it the issues disappeared.

**Comment by hyschive** [comment] 2021-09-21 12:23
@jzuhone Thanks for the update. Good to know that this issue is not caused by an intrinsic bug in GAMER. Does it also occur in earlier versions of GAMER when enabling `-std=c++11`?

FTR, what compiler are you using? And if you are using GPU, what are the CUDA version (e.g., CUDA 11.4) and GPU (e.g., A100)?

**Comment by hyschive** [comment] 2022-01-02 09:25
@jzuhone Do you think that we could close this issue?

**Comment by jzuhone** [comment] 2022-01-02 15:46
Let me see if I can cause it again, I'll try this week.

**Comment by jzuhone** [comment] 2022-02-03 03:40
@hyschive I still get this error on Pleiades. 

Volta / V100 GPU
gcc 9.3
CUDA 11.0

I did not get this error on the K40 GPUs.

**Comment by hyschive** [comment] 2022-02-03 15:11
@jzuhone Could you share the procedure for reproducing this issue (e.g., makefile options, runtime parameter files, and visualization script)? I'll see if I can reproduce it locally.

**Comment by jzuhone** [comment] 2022-02-03 19:01
@hyschive file is here: http://use.yt/upload/e64e6392

The evolution slows to a crawl in wall-clock time after dumping `Data_000001`. To see the effect on the magnetic field, simply:

```python
import yt
ds = yt.load("Data_000002")
slc = yt.SlicePlot(ds, "z", ("gas","magnetic_field_strength"))
slc.save()
```

**Comment by hyschive** [comment] 2022-02-04 14:52
![Data_000020_Slice_z_magnetic_field_strength](https://user-images.githubusercontent.com/18057331/152548199-440989dc-9bfc-484b-b002-ec2c667060f9.png)

@jzuhone I cannot reproduce this issue locally. My setup is as follows.
- Turing (NVIDIA GeForce RTX 2080 SUPER)
- gcc 9.3 or intel 2022.0.1
- CUDA 11.3

Judging from your previous [post](https://github.com/gamer-project/gamer/issues/80#issuecomment-923524157), the issue may depend on compilers. Can you try the intel compiler? Also, does Pleiades support CUDA version > 11.0?

**Comment by jzuhone** [comment] 2022-02-04 17:05
@hyschive it appears that CUDA 11.0 is the culprit here. thanks

**Comment by hyschive** [comment] 2022-02-05 03:32
@jzuhone I've added this issue [here](https://github.com/gamer-project/gamer/wiki/Troubleshooting#instability-with-mhd). Do you think that we can close it?

**Comment by jzuhone** [comment] 2022-02-05 03:33
Yes

**Closed** 2022-02-05 03:34 UTC
Labels: bug
